### PR TITLE
feat: added robot.txt/sitemap generation, small warnings

### PR DESCRIPTION
**Pull request by jonezque**
https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=35dcf02f76284d8e8efe0b67f7a04234&p=3a750a10d2444e7ba9fa1cde2a942b8f

### CODE REVIEW

**Comment by r0x4xn** [comment]
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-fg53vscct-prepo.vercel.app'>https://core-dapp-fg53vscct-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

**Review by r0x4xn — CHANGES_REQUESTED** [review]
Nice! Good initiative to fix this!

The sitemap is not building all the available pages in the application properly. We are only getting one weird url that doesn't even exist

image

**Comment by jonezque** [comment]
> Nice! Good initiative to fix this!
> 
> The sitemap is not building all the available pages in the application properly. We are only getting one weird url that doesn't even exist
> 
> image

this is correct
https://www.npmjs.com/package/next-sitemap
`From next-sitemap v2.x onwards, sitemap.xml will be [Index Sitemap](https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps). It will contain urls of all other generated sitemap endpoints.`
https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps
tested it locally,
Screenshot 2022-06-02 at 00 24 32

**Comment by r0x4xn** [comment]
@jonezque thing is that those are not being deployed/generated

image

**Review by r0x4xn — APPROVED** [review]
@jonezque yeah, my bad. I was testing on our live domain which of course hasn't the latest sitemaps deployed yet lol :) approved

**Pull request merged**
