### PR TITLE
fix: position icon on same with level with button main label

### PR DESCRIPTION
**Pull request by georgesmithishere**
https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=6291a00edd9941b2862287b361e11d13

### CODE REVIEW

**Comment by r0x4xn** [comment]
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-3hvrlrp6m-prepo.vercel.app'>https://core-dapp-3hvrlrp6m-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

**Review by chrisling-dev — CHANGES_REQUESTED** [review]
Could you check if position of the the ExternalLink icon on `Buy PPO` should be affected by this change please?

After this PR:
Screenshot 2022-06-13 at 8 10 47 AM

In production:
Screenshot 2022-06-13 at 8 11 46 AM

In design:
Screenshot 2022-06-13 at 8 12 10 AM

**Review by r0x4xn — COMMENTED** [review]
Weird that we are getting change on yarn.lock here too. Is by doing once again a yarn install?

**Comment by georgesmithishere** [comment]
> Weird that we are getting change on yarn.lock here too. Is by doing once again a yarn install?

I will check

**Pull request merged**
