### PR TITLE
feat: pnl estimation for close position

### PR DESCRIPTION
**Pull request by chrisling-dev**

### CODE REVIEW

**Review by MeLlamoPablo — APPROVED** [review]
Nice!

**Review by MeLlamoPablo — CHANGES_REQUESTED** [review]
Something seems to have broken with the simulator for open position. It doesn't suggest the max value anymore. Could you check it out?

Screenshot 2023-04-12 at 20 33 33

**Comment by chrisling-dev** [comment]
> Something seems to have broken with the simulator for open position. It doesn't suggest the max value anymore. Could you check it out?
> 
> Screenshot 2023-04-12 at 20 33 33

I am not able to reproduce this, could you provide a screen recording on how you got to this state?

**Review by MeLlamoPablo — APPROVED** [review]
Hmm weird, yesterday I got that state just by going to the preview URL. I also didn't get that state on main on localhost. So maybe it's unrelated?

Unblocking this, but could you keep an eye on prod after merging?

**Pull request merged**
