### PR TITLE
feat: use zero address across all apps

### PR DESCRIPTION
**Pull request by r0x4xn**
## Description
Use `ZERO_ADDRESS` across all monorepo coming from `prepo-packages`

Ticket related to this PR:
https://www.notion.so/Shared-files-on-smart-contracts-95b7d0d591c64f08943e82c772ff938b

### CODE REVIEW

**Review by chrisling-dev — CHANGES_REQUESTED** [review]
Screenshot 2022-06-22 at 9 38 35 PM

There's 2 files that are using the deleted `EMPTY_CONTRACT_ADDRESS`, could you also fix this? Build is failing now

**Comment by r0x4xn** [comment]
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-85c5jnb6d-prepo.vercel.app'>https://core-dapp-85c5jnb6d-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

**Review by chrisling-dev — APPROVED** [review]

**Comment by r0x4xn** [comment]
App <strong>react-boilerplate</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://react-boilerplate-hjzrd0398-prepo.vercel.app'>https://react-boilerplate-hjzrd0398-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_3Lydru5gdN5RuqWFQBT8AZrbiROq"></hidden>

**Review by ramenforbreakfast — APPROVED** [review]
LGTM! Thanks for taking care of this.

**Pull request merged**
