### PR TITLE
fix: remove package json license keys

### PR DESCRIPTION
**Pull request by r0x4xn**
https://www.notion.so/Remove-license-key-field-from-package-jsons-582a008cb87c4d85b8d7b97fab509e62

### CODE REVIEW

**Review by XavierEkkel — APPROVED** [review]

**Comment by r0x4xn** [comment]
App <strong>website</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://website-nby1y3jc3-prepo.vercel.app'>https://website-nby1y3jc3-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_OtZFmASyChHVcxNEAY2NfOQoYQ56"></hidden>

**Comment by r0x4xn** [comment]
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-d82q4tr25-prepo.vercel.app'>https://core-dapp-d82q4tr25-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

**Comment by r0x4xn** [comment]
App <strong>react-boilerplate</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://react-boilerplate-ot6rrq4jd-prepo.vercel.app'>https://react-boilerplate-ot6rrq4jd-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_3Lydru5gdN5RuqWFQBT8AZrbiROq"></hidden>

**Comment by r0x4xn** [comment]
App <strong>simulator</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://simulator-488j3gsv8-prepo.vercel.app'>https://simulator-488j3gsv8-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JqVcxQPRfkDbLp3ytm7FLLIvOPXc"></hidden>

**Pull request merged**
