### PR TITLE
feat: remove scroll in terms checklist

### PR DESCRIPTION
**Pull request by chrisling-dev**
https://www.notion.so/prepo/6ff94d2f628847cd97c80bfbe667b5b9?v=1160865fbe4c4639af9d63918c7b7d17&p=afc7144e5fbb4c6b83b217bfdb87d39f&pm=s

### CODE REVIEW

**Review by MeLlamoPablo — CHANGES_REQUESTED** [review]
I'm not necessarily against this solution, but we should note that this doesn't get rid of the scrollbar if the window height shrinks (in that case we have two scrollbars, the terms one and the body one)

Maybe we could not have `max-height` on the terms box and let the body scrollbar be the only one?

**Comment by chrisling-dev** [comment]
> I'm not necessarily against this solution, but we should note that this doesn't get rid of the scrollbar if the window height shrinks (in that case we have two scrollbars, the terms one and the body one)
> 
> Maybe we could not have `max-height` on the terms box and let the body scrollbar be the only one?

good point, addressed

**Review by MeLlamoPablo — CHANGES_REQUESTED** [review]
This change affects the terms scroll too (which also makes impossible to agree to them since we rely on the scrollbar).

We should only do this for the "rules" screen? (The notion ticket is misleading)

**Review by MeLlamoPablo — APPROVED** [review]
LGTM

**Pull request merged**
