### PR TITLE
feat: support block explorers on Onboard

### PR DESCRIPTION
**Pull request by MeLlamoPablo**
This PR passes the Arbiscan `blockExplorer` to Onboard so that if an user doesn't have the Arbitrum network on MetaMask, our app adds Arbiscan when suggesting the network to the user.

### CODE REVIEW

**Review by XavierEkkel — COMMENTED** [review]
Let's only merge this after fixing tests, testing all wallets, and looking into patch notes for potentially breaking changes from these version bumps.

**Review by chrisling-dev — COMMENTED** [review]
Tested that it works well, will approve after tests are fixed

**Review by chrisling-dev — APPROVED** [review]
LGTM!

**Comment by MeLlamoPablo** [comment]
* Tested on supported wallets
  * Metamask
  * Coinbase Wallet
  * Gnosis Safe via WalletConnect
* No breaking changes on Onboard's changelog

**Pull request merged**
