### PR TITLE
feat: add localization support to boilerplate

### PR DESCRIPTION
**Pull request by r0x4xn**
https://www.notion.so/Add-localization-support-567aab54b7af48eeb7b917e59f3133bd

### CODE REVIEW

**Comment by r0x4xn** [comment]
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-p91nt0fpn-prepo.vercel.app'>https://core-dapp-p91nt0fpn-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

**Comment by r0x4xn** [comment]
App <strong>simulator</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://simulator-pn2oosv2z-prepo.vercel.app'>https://simulator-pn2oosv2z-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JqVcxQPRfkDbLp3ytm7FLLIvOPXc"></hidden>

**Comment by r0x4xn** [comment]
App <strong>website</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://website-4eb8p721x-prepo.vercel.app'>https://website-4eb8p721x-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_OtZFmASyChHVcxNEAY2NfOQoYQ56"></hidden>

**Comment by r0x4xn** [comment]
App <strong>react-boilerplate</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://react-boilerplate-6k7twqpmj-prepo.vercel.app'>https://react-boilerplate-6k7twqpmj-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_3Lydru5gdN5RuqWFQBT8AZrbiROq"></hidden>

**Review by georgesmithishere — APPROVED** [review]
Looks great

**Pull request merged**
