### PR TITLE
fix: prevent confusion with hardhat local node and ganache local node

### PR DESCRIPTION
**Pull request by ramenforbreakfast**
I have removed the `localhost` network since the current definition can be misleading and also cause issues if someone tries to invoke something to the `localhost` network. 

The `localhost` network defined here only pertains to local nodes spun up with Ganache, which uses a chainId of 1337. This is confusing because if someone were to use a Hardhat local node and specify `localhost`, their chainId would point to the incorrect Ganache chainId.

Edit: This PR used to contain changes to network naming, but I have removed them since there are already implemented workarounds and am awaiting input from the FE team.

### CODE REVIEW

**Comment by r0x4xn** [comment]
App <strong>react-boilerplate</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://react-boilerplate-nyrvzj7qi-prepo.vercel.app'>https://react-boilerplate-nyrvzj7qi-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_3Lydru5gdN5RuqWFQBT8AZrbiROq"></hidden>

**Comment by r0x4xn** [comment]
App <strong>core-dapp</strong> has been deployed to Vercel.

<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://core-dapp-epl91aov0-prepo.vercel.app'>https://core-dapp-epl91aov0-prepo.vercel.app</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="prj_JWVJ3WoV71UcOmB52qrcezjyBL3V"></hidden>

**Review by XavierEkkel — APPROVED** [review]
LGTM

**Review by Nilay27 — APPROVED** [review]
LGTM!

**Pull request merged**
